### ISSUE TITLE
shell

### ISSUE THREAD

**Issue by yu7272yu** [JiehuiSun/sanic_script#1]
在进入shell中无法默认引用我返回的dict

**Comment by JiehuiSun** [comment]
> 在进入shell中无法默认引用我返回的dict

可以具体点么？如果方便上个代码或者截图啥的。

**Comment by yu7272yu** [comment]
![IMG_3501](https://user-images.githubusercontent.com/20694314/158318482-c8304677-5137-4540-8161-2650553fea8f.PNG)
### 代码

# -*- coding: utf-8 -*-
import sys
import oscurPath = os.path.abspath(os.path.dirname(__file__))
rootPath = os.path.split(curPath)[0]sys.path.append(rootPath)
from hx0118 import app, bind
from hx0118.database.model import *
from sqlalchemy.ext.asyncio import create_async_engine 
from sqlalchemy import select, func 
from sanic_script import Manager, Shell, Command

manager = Manager(app)
def _make_context():    
    return dict(app=app, bind=bind, User=User, Account=Account, Permission=Permission, Role=Role, UserRole=UserRole, RolePermission=RolePermission, Usergroup=Usergroup, UsergroupUser=UsergroupUser, UsergroupRole=UsergroupRole, tt="1111")
manager.add_command('shell', Shell(make_context=_make_context, use_ipython=True, use_bpython=True))

if __name__ == '__main__':    
    manager.run()

**Comment by yu7272yu** [comment]
> > 在进入shell中无法默认引用我返回的dict
> 
> 可以具体点么？如果方便上个代码或者截图啥的。

你这个sanice_script我没使用得了，我只有用了https://github.com/colinben/sanic-script这个连接的

**Comment by JiehuiSun** [comment]
> ![IMG_3501](https://user-images.githubusercontent.com/20694314/158318482-c8304677-5137-4540-8161-2650553fea8f.PNG)
> 
> ### 代码
> # -_- coding: utf-8 -_-
> import sys import oscurPath = os.path.abspath(os.path.dirname(**file**)) rootPath = os.path.split(curPath)[0]sys.path.append(rootPath) from hx0118 import app, bind from hx0118.database.model import * from sqlalchemy.ext.asyncio import create_async_engine from sqlalchemy import select, func from sanic_script import Manager, Shell, Command
> 
> manager = Manager(app) def _make_context(): return dict(app=app, bind=bind, User=User, Account=Account, Permission=Permission, Role=Role, UserRole=UserRole, RolePermission=RolePermission, Usergroup=Usergroup, UsergroupUser=UsergroupUser, UsergroupRole=UsergroupRole, tt="1111") manager.add_command('shell', Shell(make_context=_make_context, use_ipython=True, use_bpython=True))
> 
> if **name** == '**main**': manager.run()



================================

你搞错了，shell默认已经添加了的，不用再次添加了
正常manage.py里只需要这样写

`
from sanic_script import Manager
from server import app


manager = Manager(app)

if __name__ == "__main__":
    manager.run()
`

**Comment by JiehuiSun** [comment]
> 

===========================
补充： 如果你需要扩展，clone后直接修改就行，shell/runserver命令注册在__init__.py里

**Comment by yu7272yu** [comment]
> > 
> 
> =========================== 补充： 如果你需要扩展，clone后直接修改就行，shell/runserver命令注册在__init__.py里

 manager.add_command('shell', Shell(make_context=_make_context))

**Comment by yu7272yu** [comment]
> > 
> 
> =========================== 补充： 如果你需要扩展，clone后直接修改就行，shell/runserver命令注册在__init__.py里

因为我要增加# manager.add_command('shell', Shell(make_context=_make_context))以便于进入shell就默认引用的变量，我刚发现了，是那个包里commands.py中的shell方法中get_context，并没有返回我们make_context

**Comment by JiehuiSun** [comment]
> > > 
> > 
> > 
> > =========================== 补充： 如果你需要扩展，clone后直接修改就行，shell/runserver命令注册在__init__.py里
> 
> 因为我要增加# manager.add_command('shell', Shell(make_context=_make_context))以便于进入shell就默认引用的变量，我刚发现了，是那个包里commands.py中的shell方法中get_context，并没有返回我们make_context

==============================

嗯，都是返回了None，shell只是辅助工具，可以直接改或者三方shell工具，比如ipython等，也会更好的辅助shell，比如可以输入from 按上健就可以直接查找from开头的历史命令

**Comment by yu7272yu** [comment]
> > > > 
> > > 
> > > 
> > > =========================== 补充： 如果你需要扩展，clone后直接修改就行，shell/runserver命令注册在__init__.py里
> > 
> > 
> > 因为我要增加# manager.add_command('shell', Shell(make_context=_make_context))以便于进入shell就默认引用的变量，我刚发现了，是那个包里commands.py中的shell方法中get_context，并没有返回我们make_context
> 
> ==============================
> 
> 嗯，都是返回了None，shell只是辅助工具，可以直接改或者三方shell工具，比如ipython等，也会更好的辅助shell，比如可以输入from 按上健就可以直接查找from开头的历史命令

明白了，谢谢了
